### ISSUE TITLE
Multiple animation on 1 canvas

### ISSUE THREAD

**Issue by miguelmoraleda** [manuelodelain/sprite-anim#1]
Hi,

Is there a way to have multiple spritesheet animations on the same canvas container? I would like to have only 1 canvas using the whole screen and add many spritesheet animations on it.

Is it possible with the current implementation? Any ideas of how can I make that?

Thanks in advance.

Best regards,
Miguel

**Comment by manuelodelain** [comment]
Hi Miguel,

You can implement your own canvas renderer like this (not tested):

```
var Renderer = function(canvas, sprite){
  this.canvas = canvas;
  this.sprite = sprite;

  this.x = 0;
  this.y = 0;
  this.context = canvas.getContext('2d');
};

Renderer.prototype.render = function(frame) {  
  this.context.drawImage(
    this.sprite,
    frame.x,
    frame.y,
    frame.width,
    frame.height,
    this.x,
    this.y,
    frame.width,
    frame.height
   );
};
```

Instanciate the renderer:

```
var render = new Renderer(canvas, sprite);

// set the position
render.x = 100; 
render.y = 100;
```

With your render logic common to all the spritesheet anims :

```
var canvas = document.getElementById('yourCanvas');
var context = canvas.getContext('2d');

// called in/with a requestAnimationFrameLoop
function render(){
    context.clearRect(0, 0, canvas.width, canvas.height);
}
```

A possible performance bottleneck, with many sprites, could be that each SpriteAnim instance have his own requestAnimationFrame.
The solution would be a common ticker, but it's not implemented yet.

Hope it helps

**Comment by miguelmoraleda** [comment]
Thanks @manuelodelain 

I did something very similar to what you suggested. 

How do you think about having an option "manualUpdate" (default false). So if it is true you won't use raf inside the animation so people will be forced to call enterFrame manually?

**Comment by miguelmoraleda** [comment]
Sorry about closing this issue. I didn' realize you labeled as an enhancement.

I have created a OneCanvasRenderer implementation. Would you like me to make a pull request with it?

**Comment by manuelodelain** [comment]
@miguelmoraleda No problems, I have just some informations.

You can call the `onEnterFrame` method directly but you have to pass the raf `timeStamp` parameter to it (doc updated + an example).

https://github.com/manuelodelain/sprite-anim/blob/master/examples/custom-render-loop.html
https://github.com/manuelodelain/sprite-anim#onenterframetimestamp

Please let me know if it suits to your utilisation.

And now there is only one ticker (raf loop) for all the SpriteAnim instances.
I think it can be an improvement in case of many spritesheet.

For the OneCanvasRenderer, it would be nice to see your implementation :)
